#!/bin/sh

[ ! -e /root/.ssh/ ] && mkdir -p /root/.ssh/

[ -f /host/id_rsa.pub ] && cp /host/id_rsa.pub /root/.ssh/authorized_keys && chown 0.0 /root/.ssh/authorized_keys

[ -f /host/id_rsa ] && cp /host/id_rsa /root/.ssh/id_rsa && chown 0.0 /root/.ssh/id_rsa

mkdir -p /usr/local/var/log/php-fpm

mkdir -p /usr/local/var/log/php_errors

mkdir -p /usr/local/var/log/php_slow

mkdir -p /usr/local/var/log/nginx

chown www-data:www-data -R /usr/local/var

chown 0.0 -R /etc/crontabs

chown 0.0 -R /etc/logrotate.d/

chown 0.0 /etc/logrotate.conf

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
