name: Build Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [
            php80,
            php74,
            php73,
            # php72,
            # php71,
            # php70,
            # php56,
            # php55,
            # php54,
            # php53,
            # php-builder,
            # openresty117,
            # openresty119,
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        run: |
          docker build -t tofuliang/docker-php-openresty:${{ matrix.branch }} ${{ matrix.branch }}
          docker push tofuliang/docker-php-openresty:${{ matrix.branch }}
