name: DockerFile Updater

on:
  push:
    branches:
      - master
  watch:
    types: [started]
  schedule:
    - cron: 30 2 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config --global user.email "tofuliang@gmail.com"
          git config --global user.name "tofuliang"
      - name: source update
        run: |
          for b in 80 74 73;do
          ( cd php${b}; \
          cp ../update.sh update.sh; \
          chmod a+x ./update.sh && ./update.sh $b; \
          rm -fr update.sh )
          done
          git add . && git commit -m "update" && git push || true
